### ISSUE TITLE
CUDA out of memory issue

### ISSUE THREAD

**Issue by JD-ETH** [openai/phasic-policy-gradient#2]
Hi there, 
I am trying to run the example but getting the out of memory result on my 8GB RTX 2070:

> 
> /home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/runpy.py:125: RuntimeWarning: 'phasic_policy_gradient.train' found in sys.modules after import of package 'phasic_policy_gradient', but prior to execution of 'phasic_policy_gradient.train'; this may result in unpredictable behaviour
>   warn(RuntimeWarning(msg))
> Traceback (most recent call last):
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/train.py", line 106, in <module>
>     main()
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/train.py", line 103, in main
>     comm=comm)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/train.py", line 76, in train_fn
>     comm=comm,
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/ppg.py", line 256, in learn
>     **ppo_hps,
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/ppo.py", line 244, in learn
>     verbose=verbose,
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/minibatch_optimize.py", line 60, in minibatch_optimize
>     train_fn(**mb) for mb in minibatch_gen(tensordict, nminibatch=nminibatch)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/minibatch_optimize.py", line 60, in <listcomp>
>     train_fn(**mb) for mb in minibatch_gen(tensordict, nminibatch=nminibatch)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/ppo.py", line 192, in train_pi_and_vf
>     return train_with_losses_and_opt(["pi", "vf"], opts["pi"], **arrays)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/ppo.py", line 173, in train_with_losses_and_opt
>     **arrays,
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/ppo.py", line 88, in compute_losses
>     pd, vpred, aux, _state_out = model(ob=ob, first=first, state_in=state_in)
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/ppg.py", line 140, in forward
>     x_out[k], state_out[k] = self.get_encoder(k)(ob, first, state_in[k])
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/impala_cnn.py", line 182, in forward
>     x = self.cnn(x)
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/impala_cnn.py", line 149, in forward
>     x = tu.sequential(self.stacks, x, diag_name=self.name)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/torch_util.py", line 363, in sequential
>     x = layer(x, *args)
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/impala_cnn.py", line 109, in forward
>     x = block(x)
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/impala_cnn.py", line 85, in forward
>     return x + self.residual(x)
>   File "/home/jd/competition/phasic-policy-gradient/phasic_policy_gradient/impala_cnn.py", line 76, in residual
>     x = F.relu(x, inplace=False)
>   File "/home/jd/anaconda3/envs/phasic-policy-gradient/lib/python3.7/site-packages/torch/nn/functional.py", line 914, in relu
>     result = torch.relu(input)
> RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.79 GiB total capacity; 1.19 GiB already allocated; 151.88 MiB free; 1.21 GiB reserved in total by PyTorch)

I would say this is rather unreasonable? Is there anything I can do to debug?

**Comment by dkorenkevych** [comment]
I had to use a smaller minibatch size here https://github.com/openai/phasic-policy-gradient/blob/c789b00be58aa704f7223b6fc8cd28a5aaa2e101/phasic_policy_gradient/ppo.py#L120 to fit it onto my GPU

**Comment by JD-ETH** [comment]
thanks for the comment. But 256 was the optimal rollout from PPO right? I woudln't want to trade for performance.

**Comment by Dipamc77** [comment]
Since the network doesn't use batchnorm (not by default anyways), you can modify the code to accumulate gradients and get the exact same results.

**Comment by JD-ETH** [comment]
@Dipamc77 @dkorenkevych thanks for the answer. i have found that limiting the number of environment also reduces the memory footprint by a lot.

**Comment by vwxyzjn** [comment]
Please correct me if I am wrong, I think it's not the number of the environment or the number of steps that is causing the memory footprint, but rather it is because of the empty buffer `B`, as shown below:

![image](https://user-images.githubusercontent.com/5555347/96652072-2e267000-1304-11eb-94fd-4a1dfa5b1d13.png)

So the default `Nπ` is 32, which means `B` will contain of 32 * 256 (nsteps) * 64 (nenvs) = 524288 instance of observation, each of shape `(3, 64, 64)`, 1/16 (# minibatches per aux epoch per Nπ) * 524288 = 32768. Therefore in the aux phase, you are loading these obs to the GPU

```
import torch
torch.ones((32768, 3, 64,64)).to("cuda")
```

I think this is the main reason for the huge memory footprint.
