### ISSUE TITLE
VideoRecorder?

### ISSUE THREAD

**Issue by hlsafin** [openai/phasic-policy-gradient#4]
Quick question, How would you go about implementing a videorecorder so that after some number of episodes passes, you can record to view it? I can do it in a normal environment, but I think MPI is throwing things off, I'm not mistaken.

**Comment by vwxyzjn** [comment]
@hlsafin I did this: https://github.com/vwxyzjn/cleanrl/blob/53a3d0ffab83f7b0698479d79cdc0aee94f1f83d/cleanrl/ppo_procgen_fast.py#L90-L105, which results in https://wandb.ai/cleanrl/cleanrl.benchmark/runs/1b9dgx04/overview?workspace=user-costa-huang
